[package]
name = "flathub-stats"
version = "1.0.7"
edition = "2024"

[dependencies]
bitcode = { version = "0.6", features = ["serde"] }
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
